server {
    underscores_in_headers on;
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # 1. PROXY SEGURO PARA REVIEWS
    location /api-reviews/ {
        resolver 8.8.8.8 valid=30s;
        set $backend_endpoint "https://core.wappti.app/api/v1/marketing/latest-reviews";
        proxy_pass $backend_endpoint;
        proxy_set_header X-Wappti-Key "Wappti_Secure_7722_XyZ_2026";
        proxy_set_header Host core.wappti.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering off;
        proxy_ssl_server_name on;
    }
    
    # 2. CONFIGURACIÓN FLEXIBLE PARA PRIVACY-POLICY Y OTROS
    location / {
        # Esta línea es la magia:
        # $uri           -> Busca el archivo exacto (ej. privacy-policy)
        # $uri/          -> Si pides /privacy-policy/, busca un index.html dentro de una carpeta con ese nombre
        # $uri.html      -> Si no existe lo anterior, busca privacy-policy.html
        # index.html     -> Si nada coincide (como en la raíz /), carga el index.html
        try_files $uri $uri/ $uri.html /index.html =404;
    }

    # Redirección automática de "/" al final para evitar contenido duplicado (SEO y estética)
    # Si alguien escribe /privacy-policy/, Nginx lo limpia a /privacy-policy
    rewrite ^/(.*)/$ /$1 permanent;

    # Bloquear archivos ocultos
    location ~ /\. {
        deny all;
    }

    # Cache archivos estáticos
    location ~* \.(css|js|ico|png|jpg|webp|woff2)$ {
        expires 1M;
        add_header Cache-Control "public, immutable";
    }
}
